[package]
name = "enkidu_grep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lopdf = { version = "0.32.0", features = ["pom", "pom_parser"] }
ptree = "0.4.0"
vec-tree = "0.1.2"
